# Generated by Django 4.2.1 on 2024-01-30 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_audiofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="created_data",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
