# Generated by Django 4.2.1 on 2024-02-01 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ForeignKey(
                help_text="select book category ",
                on_delete=django.db.models.deletion.CASCADE,
                to="book.category",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                help_text="score 1dan katta 5 dan kichik bolishi kerak",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
